/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AssetBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Auth": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "BiographerAsync": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ContentEngine": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "ContentEngineTrigger": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ContentPayloadBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DEVTO_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DialecticalLibrarian": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "DiffPressArticleAIStream": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DiffPressDiscoverRepos": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiffPressDraftArticle": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiffPressEnrichRepos": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiffPressGenerateHandoff": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiffPressNotifyHandoff": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiffPressRecordPublication": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiffPressSeedIdeas": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiscoveryConfig": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DiscoverySignals": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GEMINI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_OWNER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_REPO": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_BOOKS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "INGEST_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IngestApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "LibrarianFetchArticles": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LibrarianFetchContext": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LibrarianPersistRecs": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LibrarianRetrieveAndCurate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LibrarianStrategicAnalysis": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LibrarianSynthesizeInsights": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LibrarianTrigger": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PINECONE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PINECONE_INDEX_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PublicationLifecycle": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TAVILY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UnifiedLake": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserPoolId": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "WebApp": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "WebClientId": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "WebhookConfig": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}