/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DreamFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "GEMINI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_OWNER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_REPO": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "INGEST_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Ingest": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PINECONE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PINECONE_INDEX_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}