import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { Resource } from "sst";
import KSUID from "ksuid";
import type { ConstellationRecord } from "../lib/schemas";

const dynamoClient = DynamoDBDocumentClient.from(new DynamoDBClient({}));
const TABLE_NAME = Resource.UnifiedLake.name;

export const handler = async (event: { markdownContent: string }): Promise<{ success: boolean }> => {
  const { markdownContent } = event;
  if (!markdownContent || markdownContent.includes("No new book recommendations")) {
    console.log("No new content to persist. Skipping update.");
    return { success: true };
  }

  try {
    const id = (await KSUID.random()).string;
    const now = new Date().toISOString();
    // Assuming user is system or admin, but schema requires USER#...
    // I'll use a specific SYSTEM user or the default admin user if I knew it.
    // However, ingest uses `event.requestContext.authorizer...`. Here it's a background job.
    // I'll use `USER#SYSTEM` for recommendations generated by the system.
    const userId = "SYSTEM"; 

    const record: ConstellationRecord = {
      PK: `USER#${userId}`,
      SK: `ENTRY#${id}`, // Using ENTRY# prefix for consistency, or I can use REC#?
      // Schema says SK is `ENTRY#${string}` | `METADATA`.
      // And type is 'Entry' | 'User' | 'Recommendation'.
      // If I want to query them easily, maybe SK should be `REC#${id}`?
      // But schema defines SK as `ENTRY#...`. I should stick to schema or update it.
      // Let's stick to SK=`ENTRY#...` and use `type` index (which I need to create or scan).
      id,
      type: "Recommendation",
      createdAt: now,
      updatedAt: now,
      content: markdownContent,
      isOriginal: true, // It's generated by AI
      mediaType: 'text',
      tags: ['recommendations', 'librarian'],
      lastAccessed: now,
      // Recommendations don't need sourceURL etc unless provided.
    };

    await dynamoClient.send(new PutCommand({
      TableName: TABLE_NAME,
      Item: record,
    }));

    console.log(`Successfully persisted recommendations to DynamoDB (ID: ${id}).`);
    return { success: true };

  } catch (error) {
    console.error(`Failed to persist recommendations:`, error);
    throw new Error("Failed to persist recommendations to DynamoDB.");
  }
};